---
- block:
    - name: Check latest beta rclone version number
      uri:
        url: https://beta.rclone.org/version.txt
        return_content: true
      register: rclone_latest_beta_version
    - name: Set variable for beta version
      set_fact:
        rclone_version: "{{ rclone_latest_beta_version.content | replace ('rclone v', '', 1) | trim }}"
        beta_version_url: https://beta.rclone.org/rclone-beta-latest-linux-{{ rclone_arch }}.zip
  when:
    - rclone_version | length == 0 and rclone_release == 'beta'

- block:
    - name: Check latest stable rclone version number
      uri:
        url: https://downloads.rclone.org/version.txt
        return_content: true
      register: rclone_latest_version
      check_mode: false
    - name: Set variable to latest stable version number
      set_fact:
        rclone_version: "{{ rclone_latest_version.content | replace ('rclone v', '', 1) | trim }}"
  when:
    - rclone_version | length == 0 and rclone_release == 'stable'
