---
- name: Update repositories cache on Ubuntu
  apt:
    update_cache: true
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ PACKAGES }}"

- name: Remove temporary working directory
  file:
    path: "{{ rclone_setup_tmp_dir }}"
    state: absent
  tags:
    - molecule-idempotence-notest

- name: Create temporary working directory
  file:
    path: "{{ rclone_setup_tmp_dir }}"
    state: directory
    mode: "0775"

- name: Get rclone stable version {{ rclone_version }}
  unarchive:
    src: https://downloads.rclone.org/v{{ rclone_version }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}.zip
    dest: "{{ rclone_setup_tmp_dir }}"
    remote_src: true
    mode: 0744
    creates: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}"
  when: rclone_release == 'stable'

- name: Get rclone beta version {{ rclone_version }}
  unarchive:
    src: "{{ beta_version_url | default('https://beta.rclone.org/v' + rclone_version + '/rclone-v' + rclone_version + '-linux-' + rclone_arch + '.zip') }}"
    dest: "{{ rclone_setup_tmp_dir }}"
    remote_src: true
    mode: 0744
    creates: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}"
  when: rclone_release == 'beta'

- name: Get list of files extracted from the rclone archive
  find:
    path: "{{ rclone_setup_tmp_dir }}"
    depth: 2
    file_type: directory
  register: rclone_archive

- name: Copy rclone binary
  copy:
    src: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}/rclone"
    dest: "/usr/local/bin/rclone"
    mode: "0755"
    owner: root
    group: root
    remote_src: true
  become: true

- name: Create config directory
  file:
    path: "{{ rclone_config_location | dirname }}"
    state: directory
    mode: "0700"
  when: rclone_configs is defined

- name: Set up rclone config
  template:
    src: rclone.conf.j2
    dest: "{{ rclone_config_location }}"
    mode: 0644
  when: rclone_configs is defined

- name: Make dir for local manpages
  file:
    path: "{{ MAN_PAGES.PATH }}"
    state: directory
    mode: "0775"
    owner: "{{ MAN_PAGES.OWNER }}"
    group: "{{ MAN_PAGES.GROUP }}"
  become: true
  when: install_manpages

- name: Copy rclone manpage
  copy:
    src: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}/rclone.1"
    dest: "{{ MAN_PAGES.PATH }}/rclone.1"
    mode: "0644"
    owner: root
    group: root
    remote_src: true
  become: true
  when: install_manpages

- name: Update mandb
  command: mandb
  become: true
  changed_when: false
  when: install_manpages

- name: Remove temporary working directory
  file:
    path: "{{ rclone_setup_tmp_dir }}"
    state: absent
  tags:
    - molecule-idempotence-notest

- name: Set up rclone fact
  template:
    src: rclone.fact.j2
    dest: /etc/ansible/facts.d/rclone.fact
    mode: 0644
